// do not edit this file - automatically generated during build
// this is the version kept in git so that there is at least something to avoid erros until compilation is run for the first time

#define COMMIT_INFO "[unknown]"

