
#define ENABLE_APCMINI
#define ENABLE_BEATSTEP
#define ENABLE_BAMBLE

#define ENABLE_LESTRUM  MIDI1
#define ENABLE_DRUMKIT  MIDI2
#define ENABLE_BITBOX   MIDI1

#define ENABLE_APCMINI_DISPLAY
#define ENABLE_BPM
#define ENABLE_SEQUENCER
#define ENABLE_CLOCKS